STEP-1: Data Loading and Analysis

In [ ]:
#important dependencies
 
import pandas as pd

#mysql toolkit
import pymysql
from sqlalchemy import create_engine

In [ ]:
df = pd.read_csv("Walmart.csv")

In [ ]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [ ]:
df.describe

<bound method NDFrame.describe of        invoice_id   Branch         City                category unit_price  \
0               1  WALM003  San Antonio       Health and beauty     $74.69
1               2  WALM048    Harlingen  Electronic accessories     $15.28
2               3  WALM067  Haltom City      Home and lifestyle     $46.33
3               4  WALM064      Bedford       Health and beauty     $58.22
4               5  WALM013       Irving       Sports and travel     $86.31
...           ...      ...          ...                     ...        ...
10046        9996  WALM056      Rowlett     Fashion accessories        $37
10047        9997  WALM030   Richardson      Home and lifestyle        $58
10048        9998  WALM050     Victoria     Fashion accessories        $52
10049        9999  WALM032        Tyler      Home and lifestyle        $79
10050       10000  WALM069     Rockwall     Fashion accessories        $62

       quantity      date      time payment_method  rating  profit_margin
0           7.0  05/01/19  13:08:00        Ewallet     9.1           0.48
1           5.0  08/03/19  10:29:00           Cash     9.6           0.48
2           7.0  03/03/19  13:23:00    Credit card     7.4           0.33
3           8.0  27/01/19  20:33:00        Ewallet     8.4           0.33
4           7.0  08/02/19  10:37:00        Ewallet     5.3           0.48
...         ...       ...       ...            ...     ...            ...
10046       3.0  03/08/23  10:10:00           Cash     3.0           0.33
10047       2.0  22/02/21  14:20:00           Cash     7.0           0.48
10048       3.0  15/06/23  16:00:00    Credit card     4.0           0.48
10049       2.0  25/02/21  12:25:00           Cash     7.0           0.48
10050       3.0  26/09/20   9:48:00           Cash     3.0           0.33

[10051 rows x 11 columns]>

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [ ]:
# checking for duplicates
df.duplicated().sum()

np.int64(51)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
# checking for null records
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.shape

(9969, 11)

In [ ]:
# now we will fix the dollar symbol problem
df['unit_price'] = df['unit_price'].str.replace('$','').astype(float)

In [ ]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [ ]:
#adding a new column named 'total_amount' 
df['total_amount'] = df['quantity'] * df['unit_price']
df.columns = df.columns.str.lower()

In [ ]:
df.head()

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total_amount
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [ ]:
# now the data is clean 
df.shape

(9969, 12)

In [ ]:
# mysql connection
engine_mysql = create_engine("mysql+pymysql://root:password@localhost:3306/walmart_db")

In [ ]:
try:
    engine_mysql
    print("successfully connected")
except:
    print("error in connection")

successfully connected

In [ ]:
df.to_sql(name='walmart', con = engine_mysql, if_exists='append',index=False)

9969